config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :kill_confirmations
  match 'players/:id' => 'players#show', via: [:get]
  match 'players' =>'players#index', via: [:get]
  resources :team_requests do
    get 'accept'
    get 'deny'
  end
  resources :teams

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]

  resources :kills

  get 'omniauth_callbacks/twitter'
  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'static_pages#home'
  match 'team_requests/accept' => 'team_requests#accept', via: [:post]
  match 'team_requests/deny' => 'team_requests#deny', via: [:post]

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]
  #kill_confirmation state machine
  match 'kill_confirmations/:id/accept' => 'kill_confirmations#accept', via: [:post]
  match 'kill_confirmations/:id/deny' => 'kill_confirmations#deny', via: [:post]
  match 'kill_confirmations/:id/veto' => 'kill_confirmations#veto', via: [:post]
  match 'kill_confirmations/:id/approve' => 'kill_confirmations#approve', via: [:post]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if !user_signed_in?
      render "landing"
    elsif !current_user.game
      render "join_game"
    elsif !current_user.team
      render "join_team"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<%if user_signed_in?%>
<p>Welcome, <%= current_user.username%>. ID: <%= current_user.id %></p>
<% end %>
<h1>Assassins</h1>


<% if current_user && current_user.team%>
  <strong>Team:</strong> <%= link_to current_user.team.name, current_user.team%>
  <h3>Teammates:</h3>
  <ul>
  <% current_user.team.users.each do |user| %>
   <% next if user == current_user %>
    <li><%= link_to user.username, player_path(user)%></li>
  <% end %>
</ul>

  <% if current_user.team.target %>
    <h3>Targets:</h3>
    <ul>
    <% current_user.team.target.users.each do |target| %>
      <li><%= link_to target.username, player_path(target)%></li>
    <% end %>
  </ul>
  <% end %>

  <%if current_user.received_kill_confirmations.count > 0 %>
   <h3>Pending Confirmations:</h3>
      <ul>
      <% current_user.received_kill_confirmations.each do |kc| %>
        <li><%= link_to kc.kill.to_sentence, kc %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/static_pages/join_game.html.erb
<p>Welcome, <%= current_user.username%>. ID: <%= current_user.id %></p>
<div class="col-md-8 col-centered">
  <h3>You haven't joined a game yet!</h3>
  <br>
  <p class="lg"> <%= link_to "Find a Game!", games_path, class: "btn btn-default btn-lg"%> or
      <%= link_to "Create Your Own!", new_game_path, class: "btn btn-default btn-lg"%>
  </p>
</div>

app/views/static_pages/join_team.html.erb
<p>Welcome, <%= current_user.username%>. ID: <%= current_user.id %></p>
<div class="col-md-8 col-centered">
  <h3>Time to join a team!</h3>
  <% if current_user.recieved_team_requests.count > 0 %>
  <br>
    <p>You've been invited to join a team!</p>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>By</th>
            <th>Team</th>
            <th colspan="3">Action</th>
          </tr>
        </thead>

        <tbody>
          <% current_user.recieved_team_requests.each do |team_request| %>
            <%= render team_request, :locals => {show: true} %>
        <% end %>
        </tbody>
      </table>
    </div>
    <p>or</p>
  <% end %>
  <%= link_to "Create a Team!", new_team_path, class: "btn btn-default btn-lg" %>
</div>

app/views/static_pages/landing.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Assassins</h1>
    <p>Create and manage games of Assassins with ease!</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a></p>
  </div>
</div>