config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :kill_confirmations
  match 'players/:id' => 'players#show', via: [:get]
  match 'players' =>'players#index', via: [:get]
  resources :team_requests do
    get 'accept'
    get 'deny'
  end
  resources :teams

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]

  resources :kills

  get 'omniauth_callbacks/twitter'
  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'static_pages#home'
  match 'team_requests/accept' => 'team_requests#accept', via: [:post]
  match 'team_requests/deny' => 'team_requests#deny', via: [:post]

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]
  #kill_confirmation state machine
  match 'kill_confirmations/:id/accept' => 'kill_confirmations#accept', via: [:post]
  match 'kill_confirmations/:id/deny' => 'kill_confirmations#deny', via: [:post]
  match 'kill_confirmations/:id/veto' => 'kill_confirmations#veto', via: [:post]
  match 'kill_confirmations/:id/approve' => 'kill_confirmations#approve', via: [:post]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, presence: true, length: {maximum: 40}
  belongs_to :owner, class_name: "User"
  has_many :users
  has_many :teams
  before_destroy :release_users_from_game

  after_save do
      self.owner.game = self
      self.owner.save!
    end

  def invite_only?
    !code == nil
  end

  def release_users_from_game
    self.users.each do |user|
      user.game_id = nil;
      user.save!
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(name: game_params[:name],
                    code: game_params[:code],
                    owner: current_user)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :code, :owner)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :game_code %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.number_field :owner, id: :game_owner %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games <span class="pull-right"><%= link_to new_game_path, class: "btn btn-default" do %>
New Game <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
<% end %>
</span></h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Invite Only</th>
        <th>Owner</th>
        <th>Players</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= link_to game.name, game %></td>
          <td><%= (bool_to_yn game.invite_only?).capitalize %></td>
          <td><%= link_to game.owner.username, player_path(game.owner) %></td>
          <td><%= game.users.count %></td>
          <% if game.owner == current_user %>
            <td><%= link_to 'Edit', edit_game_path(game) %></td>
            <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/new.html.erb
<div class="col-md-4 col-centered">
  <h1>New Game</h1>

  <%= form_for @game, html: {class: "form-horizontal center"} do |f| %>

    <div class="form-group">
      <%= f.label :name, class: "control-label"%>
      <%= f.text_field :name, class:"form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :code, class: "control-label"%>
      <div class="input-group">
        <%= f.text_field :code, placeholder: "Leave blank to allow anyone to join", class:"form-control", id:"code-field" %>
        <div id="gen-code" class="form-button input-group-addon">
          <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        </div>
      </div>

    </div>
    <div class="actions">
      <%= back_link "Back", "btn btn-default pull-left" %>
      <%= f.submit "Create and Join Team", class: "btn btn-default btn-primary pull-right" %>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>
<%if current_user == @game.owner%>
  <p>
    <strong>Code:</strong>
    <%= @game.code %>
  </p>
<% else %>
<p>
  <strong>Invite Only:</strong>
  <%= (bool_to_yn @game.invite_only?).capitalize %>
</p>
<% end %>

<p>
  <strong>Owner:</strong>
  <%= link_to @game.owner.username, player_path(@game.owner)%>
</p>

<p>
  <strong>Players:</strong>
  <%= @game.users.count %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= back_link %>