config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :kill_confirmations
  match 'players/:id' => 'players#show', via: [:get]
  match 'players' =>'players#index', via: [:get]
  resources :team_requests do
    get 'accept'
    get 'deny'
  end
  resources :teams

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]

  resources :kills

  get 'omniauth_callbacks/twitter'
  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'static_pages#home'
  match 'team_requests/accept' => 'team_requests#accept', via: [:post]
  match 'team_requests/deny' => 'team_requests#deny', via: [:post]

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]
  #kill_confirmation state machine
  match 'kill_confirmations/:id/accept' => 'kill_confirmations#accept', via: [:post]
  match 'kill_confirmations/:id/deny' => 'kill_confirmations#deny', via: [:post]
  match 'kill_confirmations/:id/veto' => 'kill_confirmations#veto', via: [:post]
  match 'kill_confirmations/:id/approve' => 'kill_confirmations#approve', via: [:post]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/team_request.rb
class TeamRequest < ApplicationRecord
  enum status: [:pending, :accepted, :denied]
  belongs_to :reciever, class_name: "User"
  belongs_to :sender, class_name: "User"
  belongs_to :team

  def accept(user)
    if user == self.reciever && self.status == "pending" && self.team
      user.team = self.team
      self.status = :accepted
      user.save! && self.save!
    end
  end

  def deny(user)
    if user == self.reciever && self.status == "pending"
      self.status = "denied"
      self.save!
    end
  end
end

app/controllers/team_requests_controller.rb
class TeamRequestsController < ApplicationController
  before_action :set_team_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /team_requests
  # GET /team_requests.json
  def index
    @invites = current_user.recieved_team_requests
    @sent = current_user.sent_team_requests
  end

  # GET /team_requests/1
  # GET /team_requests/1.json
  def show
  end

  # GET /team_requests/new
  def new
    @team_request = TeamRequest.new
  end

  # GET /team_requests/1/edit
  def edit
  end

  # POST /team_requests
  # POST /team_requests.json
  def create
      @team_request = TeamRequest.new(sender: current_user,
                                      reciever_id: team_request_params[:reciever_id],
                                      team: current_user.team)
    respond_to do |format|
      if @team_request.save
        format.html { redirect_to @team_request, notice: 'Team request was successfully created.' }
        format.json { render :show, status: :created, location: @team_request }
      else
        format.html { render :new }
        format.json { render json: @team_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_requests/1
  # PATCH/PUT /team_requests/1.json
  def update
    respond_to do |format|
      if @team_request.update(team_request_params)
        format.html { redirect_to @team_request, notice: 'Team request was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_request }
      else
        format.html { render :edit }
        format.json { render json: @team_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_requests/1
  # DELETE /team_requests/1.json
  def destroy
    if @team_request.status != "pending"
      flash[:notice] = "could not delete team request."
      redirect_to action: "index"
    else
      @team_request.destroy
      respond_to do |format|
        format.html { redirect_to team_requests_url, notice: 'Team request was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def accept
    @team_request = TeamRequest.find(params[:request_id])

    if @team_request.accept(current_user)
      #accepted successfully
      flash[:notice] = "successfully joined '#{@team_request.team.name}'"
      redirect_to @team_request.team
    else
      #error accepting request
      flash[:error] = "Could not join '#{@team_request.team.name}'."

    end
  end

  def deny
    @team_request = TeamRequest.find(params[:request_id])
    if @team_request.deny(current_user)
      #accepted successfully
      flash[:notice] = "Team Request Declined"
    else
      #error accepting request
      flash[:error] = "Error."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_request
      @team_request = TeamRequest.find(params[:id])
    end

    # Only allows reciever_id, the sender and team are inferred from current_user
    def team_request_params
      params.require(:team_request).permit(:reciever_id)
    end
end

app/helpers/team_requests_helper.rb
module TeamRequestsHelper
end

app/views/team_requests/_form.html.erb
<%= form_with(model: team_request, local: true) do |form| %>
  <% if team_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_request.errors.count, "error") %> prohibited this team_request from being saved:</h2>

      <ul>
      <% team_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.number_field :sender_id, id: :team_request_sender_id %>
  </div>

  <div class="field">
    <%= form.label :reciever_id %>
    <%= form.number_field :reciever_id, id: :team_request_reciever_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id, id: :team_request_team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/team_requests/_team_request.html.erb
<tr>
    <td><%= link_to team_request.sender.username, player_path(team_request.sender) %></td>
    <td><%= link_to team_request.team.name, team_request.team %></td>
    <td><span>
    <% #if show %>
      <%= button_to 'View', {:controller => "team_requests", :action => "show", :id => team_request.id} , :method=>:get, class:"btn btn-default btn-sm btn-left"  %>
    <% #end %>
    <%= button_to 'Accept', {:controller => "team_requests", :action => "accept", :request_id => team_request.id} , :method=>:post, class:"btn btn-default btn-sm btn-left"  %>
    <%= button_to 'Deny', {:controller => "team_requests", :action => "deny", :request_id => team_request.id} , :method=>:post, class:"btn btn-default btn-sm btn-left"  %></span></td>
</tr>

app/views/team_requests/edit.html.erb
<h1>Editing Team Request</h1>

<%= render 'form', team_request: @team_request %>

<%= link_to 'Show', @team_request %> |
<%= link_to 'Back', team_requests_path %>

app/views/team_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invites.each do |team_request| %>
      <%= render team_request %>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user.team %>
  <h1>Sent</h1>

  <table>
    <thead>
      <tr>
        <th>To</th>
        <th>Team</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @sent.each do |team_request| %>
        <tr>
          <td><%= team_request.reciever.username %></td>
          <td><%= team_request.team.name %></td>
          <td><%= team_request.status %></td>
          <% if team_request.status == "pending" %>
            <td><%= button_to 'Rescind', team_request, method: :delete, data: { confirm: 'Rescind Invitation?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if current_user.team %>
    <%= link_to "Invite user to #{current_user.team.name}", new_team_request_path %>
  <% end %>
<% end %>

app/views/team_requests/new.html.erb
<div class="col-md-4 col-centered">
  <h1>Invite User to <%= current_user.team.name%></h1>
  <%= form_for @team_request, html: {class: "form-horizontal center"} do |f| %>
    <div class="form-group">
    <%= f.label :reciever_id, class: "control-label" %><br />
    <%= f.collection_select :reciever_id, User.order(:username), :id, :username, {prompt: "Select User"}, {class:"form-control"} %>
    </div>
    <div class="actions">
      <%= f.submit "Send Request", class:"btn btn-default btn-primary pull-right" %>
      <%= link_to 'Back', team_requests_path, class: "btn btn-default pull-left" %>
    </div>
  <% end %>
</div>

app/views/team_requests/show.html.erb
<h2>Team Request<h2>

<p>
  <strong>Status:</strong>
  <%= @team_request.status %>
</p>  
<p>
  <strong>From:</strong>
  <%= @team_request.sender.username %>
</p>

<p>
  <strong>To:</strong>
  <%= @team_request.reciever.username %>
</p>

<p>
  <strong>Team:</strong>
  <%= @team_request.team.name %>
</p>

<%= link_to 'Edit', edit_team_request_path(@team_request) %> |
<%= link_to 'Back', team_requests_path %>