config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :kill_confirmations
  match 'players/:id' => 'players#show', via: [:get]
  match 'players' =>'players#index', via: [:get]
  resources :team_requests do
    get 'accept'
    get 'deny'
  end
  resources :teams

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]

  resources :kills

  get 'omniauth_callbacks/twitter'
  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'static_pages#home'
  match 'team_requests/accept' => 'team_requests#accept', via: [:post]
  match 'team_requests/deny' => 'team_requests#deny', via: [:post]

  match 'kills/new', to: 'kill_confirmations#new', via: [:get]
  #kill_confirmation state machine
  match 'kill_confirmations/:id/accept' => 'kill_confirmations#accept', via: [:post]
  match 'kill_confirmations/:id/deny' => 'kill_confirmations#deny', via: [:post]
  match 'kill_confirmations/:id/veto' => 'kill_confirmations#veto', via: [:post]
  match 'kill_confirmations/:id/approve' => 'kill_confirmations#approve', via: [:post]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Assassins", root_url, class: "navbar-brand"%>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'static_pages'&& params[:action] == 'home' %>"><a href="#">Home</a></li>
        <li class="<%= 'active' if params[:controller] == 'static_pages' && params[:action] == 'about' %>"><a href="#">About</a></li>
        <li class="<%= 'active' if params[:controller] == 'teams' %>"><%= link_to "Teams", teams_path %></li>
        <li class="<%= 'active' if params[:controller] == 'kills' ||  params[:controller] == 'kill_confirmations' %>"><%= link_to "Kills", kills_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "my page", player_path(current_user) %></li>
            <li><%= (link_to current_user.team.name, current_user.team) unless !current_user.team %></li>
            <li><%= (link_to current_user.game.name, current_user.game)  unless !current_user.game %></li>
            <li role="separator" class="divider"></li>

            <li class="dropdown-header">Actions</li>
            <% if current_user.team %>
              <li><%= link_to "Report Kill", new_kill_confirmation_path %></li>
              <li><%= link_to "Invite Player to Team", new_team_request_path %></li>
            <% else %>
              <li><%= link_to "Report Kill", new_kill_confirmation_path %></li>
              <li><%= link_to "Invite Player to Team", new_team_request_path %></li>
            <% end %>
          </ul>
        </li>

        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In with Twitter", user_twitter_omniauth_authorize_path %></li>
        <li> <%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/_team_status.html.erb
<p>
  <strong>Status:</strong>
  <span class="label label-<%= boostrap_color_from_status team.status%>"><%= team.status.capitalize %></span>
</p>
<% if team.status != "alive" %>
  <p>
    <strong>Hit:</strong>
    <%= time_ago_in_words team.hittime %> ago.
  </p>
  <p>
    <strong>By:</strong> <%=link_to team.assassin.name, team.assassin %>
    <ul>
    <% team.assassin.users.each do |user| %>
    <li><%= link_to user.username, player_path(user) %></li>
    <% end %>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assassins</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= raw javascript_include_view_js %>

  </head>

  <body>
    <div class="container">
      <%= render "layouts/nav" %>
    <% flash.each do |key, value| %>
    <% key = "info" if key == "notice"%>
      <div class="alert alert-<%= key %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>